#!/bin/bash

source /etc/sysconfig/check-updates

TMP=$(mktemp -d)

trap "rm -rf $TMP" EXIT
trap "echo 'Received SIGUSR1'" SIGUSR1

mtime=$(stat -c '%Y' $CACHE/check_updates 2>/dev/null)
due=$((${mtime:-0} + (RANDOM % INTERVAL_RAND + INTERVAL_FIXED) * 60))
now=$(date '+%s')
delay=$((due > now ? due - now : 1))
retry=1
while true; do
	echo "Sleeping $delay second(s)"
	sleep $delay &
	cpid=$!
	# Note: the 2nd `wait` is there to suppress a message like this:
	#       check_updates_daemon: line 44: 12215 Terminated
	wait $cpid || kill $cpid && wait $cpid 2>/dev/null

	echo "Starting cache update ($retry)"
	$LIB/check_updates $OPTS 1>$TMP/out 2>$TMP/err
	ret=$?
	echo $ret >$TMP/ret
	if [[ $ret -eq 3 && $retry -lt 3 ]] && grep -q "Error while executing" $TMP/out; then
		delay=300
		retry=$((retry + 1))
		continue
	fi
	tar cf $CACHE/.check_updates.tmp -C $TMP --remove-files out err ret
	mv -f $CACHE/.check_updates.tmp $CACHE/check_updates
	echo "Finished cache update ($ret)"
	delay=$(((RANDOM % INTERVAL_RAND + INTERVAL_FIXED) * 60))
	retry=1
done
