#!/bin/bash

source /etc/sysconfig/check-updates

TMP=$(mktemp -d)

cleanup() {
	rm -rf $TMP
}

signal() {
	echo "Received signal"
}

# Note: `sleep` is killed with the USR1 signal to avoid printing a job status
# message to stderr (e.g. "check_updates_daemon: line 44: 12215 Terminated").
# This is a hack that relies on the fact that job status is not printed if
# the job dies of a signal that's trapped, and we're already trapping USR1.
# See notify_of_job_status() in jobs.c for details.
int_sleep() {
	sleep $1 &
	local cpid=$!
	wait $cpid || kill -USR1 $cpid
}

trap cleanup EXIT
trap signal SIGUSR1

while true; do
	if [[ -f $CACHE/check_updates ]]; then
		int_sleep $(((RANDOM % 30 + 240) * 60))
	fi
	echo "Starting cache update"
	retry=3
	while [[ $retry -gt 0 ]]; do
		retry=$((retry - 1))
		$LIB/check_updates $OPTS 1>$TMP/out 2>$TMP/err
		ret=$?
		echo $ret >$TMP/ret
		if [[ $ret -eq 3 ]] && grep -q "Error while executing" $TMP/out; then
			int_sleep 30
			continue
		fi
		break
	done
	tar cf $CACHE/.check_updates.tmp -C $TMP --remove-files out err ret
	mv -f $CACHE/.check_updates.tmp $CACHE/check_updates
	echo "Finished cache update"
done
